### ISSUE TITLE
Is it possible to reuse cookies for next request

### ISSUE THREAD

**Issue by yylzcom** [jaymoulin/guzzlehttp-cloudflare#1]
If my guess is right, the current situation is a new cookies generated when a request made. Once the request ends, the cookies file delete.

Is it possible to reuse the cookies?

For example, I need to get a token from login page and post it along with username and password, that means I need to make a least two request. When I get proper token and post, it returns 503 error.

Thanks and best regards!

**Comment by yylzcom** [comment]
Or any example code will be very helpful.

**Comment by jaymoulin** [comment]
Made some tests myself with the same cookie but wasn't able to bypass cloudflare without getting a new one. Let me know if you can find a solution so I merge your PR / implement.

**Comment by jaymoulin** [comment]
Do you mind giving an example so I can understand why you NEED to do that?

**Comment by yylzcom** [comment]
Jaymoulin,

Thank you for your promote reply and test.

I need to fetch some data from a page that need to login. For both login and CloudFlare-bypassing purpose, the cookies required.

In current situation, when I fetch a token from login page, and then post it along with username and password, it returns a CloudFlare 503 page(it should returns the requested website page instead of Cloudflare 503 page).

**Comment by yylzcom** [comment]
For expamle, I want to fetch the contents of https://bwh1.net/clientarea.php?action=products, this require process:

1. Bypass the CloudFlare and get the cookies
2. Get the token from login page https://bwh1.net/clientarea.php
3. Post the token, username and password to https://bwh1.net/dologin.php 
4. Then fetch the target url: https://bwh1.net/clientarea.php?action=products

Without correct cookies of CloudFlare, the POST request will be failed because the authentication info will not reach dologin.php but a CloudFlare 503 page(Yes, this sucks).

**Comment by jaymoulin** [comment]
I published a new version that should handle cookies so that you could log to your site. It regenerates a token cookie but it should work. let me know

**Comment by yylzcom** [comment]
@jaymoulin 

This version works fine! Thank you soooo much!

Just a small problem:
Undefined index: verbose_mode in ./vendor/kyranrana/cloudflare-bypass/src/CloudflareBypass/CFBypasser.php on line 126

I guess this verbose_mode is undefined, are you gonna fix it in your code, or just let users to do the define?
