### ISSUE TITLE
The old version(KyranRana/cloudflare-bypass) doesn't work

### ISSUE THREAD

**Issue by onemans-battle** [jaymoulin/guzzlehttp-cloudflare#10]
https://github.com/KyranRana/cloudflare-bypass/commit/97f4af8c1fed1ee43e902a0a4abad7654ae72365 Only this version works, and the old version can no longer bypass cloudflare. 
The bypass mechanism has changed, but has not yet been released see https://github.com/KyranRana/cloudflare-bypass/issues/146.
maybe we can change the composer.json file to depends on the master branch node?
Just a suggestion

**Comment by jaymoulin** [comment]
That's a relevant suggestion but not possible yet due to the release process adopted by Kyran on its repository for now. I already opened an issue (https://github.com/KyranRana/cloudflare-bypass/issues/157) to get rid of this and being able to be autonomous.
