### ISSUE TITLE
Add @ to tempnam()

### ISSUE THREAD

**Issue by seanquijote** [jaymoulin/guzzlehttp-cloudflare#2]
Hi! I would like to request this information to be added in your README.md.

`tempnam()` will throw an exception in PHP 7.1.0 and above. 
Placing an address operator `@` to `tempnam()` will silence the exception.

```
$oClient = new \GuzzleHttp\Client([
    'cookies' => new \GuzzleHttp\Cookie\FileCookieJar(@tempnam('/tmp', __CLASS__)),
    'headers' => ['Referer' => $sUrl],
]); // 1. Create Guzzle instance
```

**Comment by jaymoulin** [comment]
`tempnam` throws exception for a reason. You have to handle it or understand why it's throwing an exception. You're not supposed to silence this
