### ISSUE TITLE
How can I enable cache?

### ISSUE THREAD

**Issue by myscode** [jaymoulin/guzzlehttp-cloudflare#3]
Caches clearance tokens so subsequent.
The default value of the cache variable is `'cache' => false`
I guess I have to add `'cache' => new \CloudflareBypass\Storage(storage_path('cloudflare_cache'))` but how and where can I write it?

**Comment by jaymoulin** [comment]
TL;DR; Consider you can't.

Explaination:

As you noticed yourself, my code is just a wrapper to make `CloudflareBypass` Guzzle compatible.
The storage feature appeared almost a month ago but the original maintainer (KyranRana) does not publish stable release which makes releasing new version hazardous (https://github.com/KyranRana/cloudflare-bypass/issues/81)

I'll make a patch to handle this new version but you'll have to use an unstable release for this feature to be available

**Comment by jaymoulin** [comment]
FYI, I will not merge this in master since it's a non-stable version and it's breaking unit tests (fatal error in CloudFlare bypass). The source library needs to be fixed.

This will only be merged on a working stable source version.

**Comment by myscode** [comment]
It doesn't work after upgrading to `dev-master` the **kyranrana/cloudflare-bypass**.
Your commit [2c8a4b7](https://github.com/jaymoulin/guzzlehttp-cloudflare/commit/2c8a4b778250371fd58e251180c3d66a387e2f29) works perfectly without the fixing `composer.json` **kyranrana/cloudflare-bypass: v2.0**, but crashes with **kyranrana/cloudflare-bypass: dev-master**

**Comment by myscode** [comment]
Great work! Thanks a lot
