### ISSUE TITLE
Notice: Undefined variable: sPathToYouCacheFolder in C:\wamp64\www\cloudflare\index.php on line 9

### ISSUE THREAD

**Issue by kazemsoft** [jaymoulin/guzzlehttp-cloudflare#5]
I have this error after using your code:

( ! ) Notice: Undefined variable: sPathToYouCacheFolder in C:\wamp64\www\cloudflare\index.php on line 9
--

1 | 0.0010 | 402112 | {main}( ) | ...\index.php:0

**Comment by jaymoulin** [comment]
OK, I admit my doc may not be the best documentation ever, but i'm pretty sure you should have some PHP skills to debug this on your own.

1. index.php is your code
1. undefined variable means a variable is not defined (I guess, but I may be wrong ;))
1. this is just a documentation where you should define the 'path to your cache folder' (also this is optional)

Please be careful with this repo. This is not intended to do negative things to Cloudflare protected backend

**Comment by kazemsoft** [comment]
thanks for replying I do really change the variable with some folder name in root folder but yet errors continue:

( ! ) Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\wamp64\www\cloudflare\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186
--



1 | 0.0010 | 403568 | {main}( ) | ...\index.php:0
2 | 0.0090 | 499512 | GuzzleHttp\Client->request( ) | ...\index.php:15
3 | 0.5630 | 611680 | GuzzleHttp\Promise\RejectedPromise->wait( ) | ...\Client.php:131

**Comment by jaymoulin** [comment]
Once again, the message is pretty clear. You try to use the repo to pass a self-signed certificate which is not the purpose of this package
