### ISSUE TITLE
Updta code to new version of KyranRana/cloudflare-bypass

### ISSUE THREAD

**Issue by filipemansano** [jaymoulin/guzzlehttp-cloudflare#6]
PHP Fatal error:  Uncaught Error: Class 'CloudflareBypass\RequestMethod\Stream' not found

https://github.com/KyranRana/cloudflare-bypass/tree/master/src/main

**Comment by jaymoulin** [comment]
Fixed by https://github.com/jaymoulin/guzzlehttp-cloudflare/commit/746859f3dcf90ebd7d90655c42d01bae35bdf060. (https://github.com/jaymoulin/guzzlehttp-cloudflare/releases/tag/1.0.0)

Should fix https://github.com/KyranRana/cloudflare-bypass/issues/128 as well
